"use client";
import { useAuthActions } from "@convex-dev/auth/react";
import { Mail, Phone, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
export function AuthForm({ mode }: { mode: "signup" | "login" }) {
 const { signIn }=useAuthActions(); const router=useRouter(); const [method,setMethod]=useState<"email"|"phone">("email"); const [otpSent,setOtpSent]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget);try{sessionStorage.setItem("scholarship-auth-method",method);if(method==="email"){await signIn("password",{email:String(form.get("email")),password:String(form.get("password")),flow:mode==="signup"?"signUp":"signIn"});router.push("/scholarship");}else{const phone=String(form.get("phone"));const code=String(form.get("code")??"");if(!otpSent){await signIn("phone",{phone});setOtpSent(true);}else{await signIn("phone",{phone,code});router.push("/scholarship");}}}catch(err){setError(err instanceof Error?err.message:"Authentication failed");}finally{setBusy(false);}}
 return <div className="min-h-[70vh] bg-stone-50 px-4 pb-14 pt-32"><div className="mx-auto max-w-md rounded-2xl border border-stone-200 bg-white p-6 shadow-lg sm:p-8"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-xl bg-red-50 text-red-600"><ShieldCheck /></div><p className="eyebrow">Scholarship portal</p><h1 className="mt-2 font-display text-3xl font-semibold">{mode==="signup"?"Create student account":"Welcome back"}</h1><p className="mt-2 text-sm text-stone-600">Choose the sign-in method that works best for you.</p><div className="mt-6 grid grid-cols-2 gap-2 rounded-xl bg-stone-100 p-1"><button onClick={()=>{setMethod("email");setOtpSent(false)}} className={`flex items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-sm font-semibold ${method==="email"?"bg-white text-red-600 shadow-sm":"text-stone-600"}`}><Mail size={16}/> Email</button><button onClick={()=>setMethod("phone")} className={`flex items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-sm font-semibold ${method==="phone"?"bg-white text-red-600 shadow-sm":"text-stone-600"}`}><Phone size={16}/> Phone OTP</button></div><form onSubmit={submit} className="mt-6 space-y-4">{method==="email"?<><Field name="email" label="Email address" type="email" placeholder="student@example.com"/><Field name="password" label="Password" type="password" placeholder="Minimum 8 characters" minLength={8}/></>:<><Field name="phone" label="Phone number" type="tel" placeholder="03XX XXXXXXX" readOnly={otpSent}/>{otpSent&&<Field name="code" label="6-digit verification code" inputMode="numeric" pattern="[0-9]{6}" placeholder="123456"/>}</>}{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-red-600 px-4 py-3 font-semibold text-white hover:bg-red-700 disabled:opacity-60">{busy?"Please wait…":method==="phone"&&!otpSent?"Send verification code":mode==="signup"?"Create account":"Sign in"}</button></form><p className="mt-6 text-center text-sm text-stone-600">{mode==="signup"?"Already registered? ":"New student? "}<Link className="font-semibold text-red-600" href={mode==="signup"?"/scholarship/login":"/scholarship/signup"}>{mode==="signup"?"Sign in":"Create account"}</Link></p></div></div>;
}
function Field(props: React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...rest}=props;return <label className="block text-sm font-medium text-stone-700">{label}<input required {...rest} className="mt-1.5 w-full rounded-xl border border-stone-300 bg-white px-3 py-3 text-stone-900 outline-none focus:border-red-500 focus:ring-2 focus:ring-red-100"/></label>}