/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import {useAuthActions} from "@convex-dev/auth/react";
import {useConvexAuth,useMutation,useQuery} from "convex/react";
import {ConvexError} from "convex/values";
import {api} from "@/convex/_generated/api";
import type {Id} from "@/convex/_generated/dataModel";
import {Download,FileUp,LogOut,Plus,Search,UserPlus,Users} from "lucide-react";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
type DocType="cnic"|"income_certificate"|"photo"|"bank_details";
const input="rounded-xl border border-stone-300 bg-white px-3 py-2.5 text-sm";
export default function Page(){
 const {isAuthenticated,isLoading}=useConvexAuth(),{signOut}=useAuthActions();
 const ensure=useMutation(api.users.ensureCurrentUser),me=useQuery(api.users.me,isAuthenticated?{}:"skip");
 const stats=useQuery(api.admin.dashboard,me?.role==="admin"?{}:"skip");
 const [status,setStatus]=useState(""),[payment,setPayment]=useState(""),[institute,setInstitute]=useState(""),[program,setProgram]=useState("");
 const rows=useQuery(api.admin.listStudents,me?.role==="admin"?{status:(status||undefined)as any,payment:(payment||undefined)as any,institute:institute||undefined,program:program||undefined}:"skip");
 const [selected,setSelected]=useState<Id<"appUsers">|null>(null),student=useQuery(api.admin.getStudent,selected?{studentId:selected}:"skip");
 const create=useMutation(api.admin.createStudent),saveProfile=useMutation(api.admin.updateStudentProfile),review=useMutation(api.admin.reviewApplication),addTerm=useMutation(api.admin.addTerm),savePayment=useMutation(api.admin.updatePayment),uploadUrl=useMutation(api.admin.generateUploadUrl),saveDoc=useMutation(api.admin.saveStudentDocument),saveResult=useMutation(api.admin.saveTermResult);
 const exportRows=useQuery(api.admin.exportRows,me?.role==="admin"?{}:"skip");
 const [showCreate,setShowCreate]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(isAuthenticated&&me===null)void ensure({authMethod:sessionStorage.getItem("scholarship-auth-method")==="phone"?"phone":"email"});},[isAuthenticated,me,ensure]);
 if(isLoading)return <Loading/>;if(!isAuthenticated)return <Gate text="Sign in with an authorized admin account."/>;if(me&&!stats&&me.role!=="admin")return <Gate text="This account does not have admin access."/>;if(!stats||!rows)return <Loading/>;
 const val=(f:FormData,k:string)=>String(f.get(k)??"").trim(),opt=(f:FormData,k:string)=>val(f,k)||undefined;
 async function createSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const el=e.currentTarget,f=new FormData(el);try{const id=await create({fullName:val(f,"fullName"),guardianName:val(f,"guardianName"),cnic:opt(f,"cnic"),instituteName:val(f,"instituteName"),program:val(f,"program"),contactNumber:opt(f,"contactNumber"),dateOfBirth:opt(f,"dateOfBirth"),address:opt(f,"address")});el.reset();setSelected(id);setShowCreate(false);setMessage("Student added. This record is managed by admin staff.");}catch(x){setMessage(err(x));}finally{setBusy(false)}}
 async function profileSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);const f=new FormData(e.currentTarget);try{await saveProfile({studentId:selected,fullName:val(f,"fullName"),guardianName:val(f,"guardianName"),cnic:opt(f,"cnic"),instituteName:val(f,"instituteName"),program:val(f,"program"),contactNumber:opt(f,"contactNumber"),dateOfBirth:opt(f,"dateOfBirth"),address:opt(f,"address"),email:opt(f,"email"),bankAccountDetails:opt(f,"bankAccountDetails")});setMessage("Profile updated.");}catch(x){setMessage(err(x))}finally{setBusy(false)}}
 async function appSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!student?.application)return;const f=new FormData(e.currentTarget);try{await review({applicationId:student.application._id,status:val(f,"status")as any,notes:opt(f,"notes")});setMessage("Application updated.")}catch(x){setMessage(err(x))}}
 async function termSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const el=e.currentTarget,f=new FormData(el);try{const id=await addTerm({studentId:selected,termName:val(f,"termName"),amountDue:Number(f.get("amountDue")),notes:opt(f,"notes")});const file=f.get("result");if(file instanceof File&&file.size)await resultUpload(id,file);el.reset();setMessage("Term added.")}catch(x){setMessage(err(x))}}
 async function paymentSubmit(e:FormEvent<HTMLFormElement>,termId:Id<"terms">){e.preventDefault();const f=new FormData(e.currentTarget);try{await savePayment({termId,status:val(f,"status")as any,amountPaid:Number(f.get("amountPaid")),amountDue:Number(f.get("amountDue")),paymentDate:opt(f,"paymentDate"),notes:opt(f,"notes")});setMessage("Payment updated.")}catch(x){setMessage(err(x))}}
 async function store(file:File){const url=await uploadUrl({}),res=await fetch(url,{method:"POST",headers:{"Content-Type":file.type},body:file});if(!res.ok)throw new Error("File upload failed");return (await res.json()).storageId as Id<"_storage">}
 async function documentUpload(type:DocType,file:File,replaceDocumentId?:Id<"documents">){if(!selected)return;setBusy(true);try{await saveDoc({studentId:selected,type,storageId:await store(file),fileName:file.name,replaceDocumentId});setMessage(replaceDocumentId?"Document replaced.":"Document uploaded.")}catch(x){setMessage(err(x))}finally{setBusy(false)}}
 async function resultUpload(termId:Id<"terms">,file:File){await saveResult({termId,storageId:await store(file),fileName:file.name});setMessage("Result uploaded.")}
 function download(){if(!exportRows)return;const keys=["cnic","name","institute","program","applicationStatus","term","paymentStatus","amountPaid","amountDue","paymentDate"]as const,headers=["CNIC","Name","Institute","Program","Application Status","Term","Payment Status","Amount Paid","Amount Due","Payment Date"];const csv=[headers.join(","),...exportRows.map((r:any)=>keys.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`).join(","))].join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="scholarship-records.csv";a.click();URL.revokeObjectURL(a.href)}
 return <main className="min-h-screen bg-stone-50 px-4 pb-12 pt-28"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap justify-between gap-4"><div><p className="eyebrow">Scholarship administration</p><h1 className="mt-2 font-display text-3xl font-semibold">Admin dashboard</h1></div><div className="flex flex-wrap gap-2"><Button onClick={()=>setShowCreate(!showCreate)}><UserPlus size={16}/>Add Student Manually</Button><Button light onClick={download}><Download size={16}/>Export CSV</Button><Button dark onClick={()=>void signOut()}><LogOut size={16}/>Sign out</Button></div></header>{message&&<p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm">{message}</p>}
 <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Students",stats.totalStudents],["New pending",stats.pendingApplications],["Approved",stats.approved],["Rejected",stats.rejected],["Disbursed",`PKR ${stats.totalDisbursed.toLocaleString()}`],["Payments due",stats.pendingPayments]].map(([l,v])=><Metric key={l} label={String(l)} value={v}/>)}</div>
 {showCreate&&<section className="mt-7 rounded-2xl border-2 border-red-100 bg-white p-6"><h2 className="font-display text-2xl font-semibold">Add Student Manually</h2><p className="mt-1 text-sm text-stone-600">No account or student login required.</p><form onSubmit={createSubmit} className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field name="fullName" label="Student name"/><Field name="guardianName" label="Guardian name"/><Field name="cnic" label="CNIC / B-Form (optional)" optional/><Field name="instituteName" label="School name"/><Field name="program" label="Class"/><Field name="contactNumber" label="Guardian contact (optional)" optional/><Field name="dateOfBirth" label="Date of birth (optional)" type="date" optional/><Field name="address" label="Address (optional)" optional/><button disabled={busy} className="rounded-xl bg-red-600 px-4 py-3 font-semibold text-white sm:col-span-2 lg:col-span-3">{busy?"Adding?":"Add student record"}</button></form></section>}
 <div className="mt-7 grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><section className="h-fit rounded-2xl border bg-white p-5"><h2 className="flex items-center gap-2 font-display text-xl font-semibold"><Users className="text-red-600"/>Students</h2><div className="mt-4 grid grid-cols-2 gap-2"><input className={input} placeholder="Exact institute" value={institute} onChange={e=>setInstitute(e.target.value)}/><input className={input} placeholder="Exact class" value={program} onChange={e=>setProgram(e.target.value)}/><Select value={status} set={setStatus} options={["pending","under_review","approved","rejected"]}/><Select value={payment} set={setPayment} options={["pending","partial","paid"]}/></div><div className="mt-4 max-h-[760px] space-y-2 overflow-auto">{rows.map((r:any)=><button key={r.profile._id} onClick={()=>setSelected(r.profile.userId)} className={`w-full rounded-xl border p-3 text-left ${selected===r.profile.userId?"border-red-500 bg-red-50":"border-stone-200"}`}><div className="flex justify-between"><b className="text-sm">{r.profile.fullName}</b><Status value={r.application?.status||"pending"}/></div><p className="mt-1 text-xs text-stone-500">{r.profile.instituteName} ? {r.profile.program}</p></button>)}</div></section>
 <section className="rounded-2xl border bg-white p-5 sm:p-6">{!student?<div className="grid min-h-80 place-items-center text-center text-stone-500"><div><Search className="mx-auto mb-3"/>Select a student to edit their record.</div></div>:<div><div className="flex flex-wrap justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-2xl font-semibold">{student.profile?.fullName}</h2><Badge admin={student.user.accountType==="admin_added"||!student.user.authUserId}/></div><p className="mt-1 text-xs text-stone-500">Last updated {new Date(student.profile?.updatedAt??student.user.updatedAt).toLocaleString()}</p></div><Status value={student.application?.status||"pending"}/></div>
 {student.profile&&<form key={student.profile.updatedAt} onSubmit={profileSubmit} className="mt-5 grid gap-3 rounded-xl bg-stone-50 p-4 sm:grid-cols-2"><Field name="fullName" label="Student name" value={student.profile.fullName}/><Field name="guardianName" label="Guardian name" value={student.profile.guardianName||student.profile.fatherName}/><Field name="cnic" label="CNIC / B-Form" value={student.profile.cnic} optional/><Field name="instituteName" label="School / institute" value={student.profile.instituteName}/><Field name="program" label="Class / program" value={student.profile.program}/><Field name="contactNumber" label="Guardian contact" value={student.profile.contactNumber} optional/><Field name="dateOfBirth" label="Date of birth" type="date" value={student.profile.dateOfBirth} optional/><Field name="email" label="Email" type="email" value={student.profile.email} optional/><Field name="address" label="Address" value={student.profile.address} optional/><Field name="bankAccountDetails" label="Bank details" value={student.profile.bankAccountDetails} optional/><button disabled={busy} className="rounded-xl bg-red-600 px-4 py-3 font-semibold text-white sm:col-span-2">Save profile changes</button></form>}
 <Documents docs={student.documents} busy={busy} upload={documentUpload}/>{student.application&&<form onSubmit={appSubmit} className="mt-6 grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><select name="status" defaultValue={student.application.status} className={input}><option value="pending">Pending</option><option value="under_review">Under review</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><input name="notes" className={input} defaultValue={student.application.reviewNotes} placeholder="Review notes"/><button className="rounded-xl bg-red-600 px-4 py-3 font-semibold text-white sm:col-span-2">Update application</button></form>}
 <h3 className="mt-7 font-display text-xl font-semibold">Terms, results & payments</h3><form onSubmit={termSubmit} className="mt-3 grid gap-2 rounded-xl bg-stone-50 p-4 sm:grid-cols-2"><input required name="termName" className={input} placeholder="New term / semester"/><input required min="0" name="amountDue" type="number" className={input} placeholder="Amount due"/><input name="notes" className={input} placeholder="Notes"/><input name="result" type="file" accept=".pdf,image/jpeg,image/png,image/webp" className={input}/><button className="rounded-xl bg-stone-900 px-4 py-3 font-semibold text-white sm:col-span-2"><Plus size={15} className="inline"/> Add term</button></form>
 <div className="mt-3 space-y-3">{student.terms.map((t:any)=><form key={t._id} onSubmit={e=>paymentSubmit(e,t._id)} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><b>{t.termName}</b><div>{t.resultUrl&&<a className="mr-2 text-sm font-semibold text-red-600" href={t.resultUrl} target="_blank">View result</a>}<label className="cursor-pointer rounded-lg border px-3 py-1.5 text-xs font-semibold"><FileUp size={13} className="inline"/> {t.resultUrl?"Replace":"Add"} result<input hidden type="file" accept=".pdf,image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void resultUpload(t._id,f).catch(x=>setMessage(err(x)))}}/></label></div></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><select name="status" defaultValue={t.paymentStatus} className={input}><option value="pending">Pending</option><option value="partial">Partially paid</option><option value="paid">Paid</option></select><input name="paymentDate" type="date" defaultValue={t.paymentDate} className={input}/><input required min="0" name="amountPaid" type="number" defaultValue={t.amountPaid} className={input}/><input required min="0" name="amountDue" type="number" defaultValue={t.amountDue} className={input}/><input name="notes" defaultValue={t.notes} className={`${input} sm:col-span-2`} placeholder="Payment notes"/><button className="rounded-xl bg-red-600 px-4 py-2.5 font-semibold text-white sm:col-span-2">Save term & payment</button></div><p className="mt-2 text-right text-xs text-stone-400">Updated {new Date(t.updatedAt).toLocaleString()}</p></form>)}</div></div>}</section></div></div></main>}
function Documents({docs,busy,upload}:{docs:any[];busy:boolean;upload:(t:DocType,f:File,r?:Id<"documents">)=>void}){const types:[DocType,string][]=[["cnic","CNIC / B-Form"],["income_certificate","Income certificate"],["photo","Student photo"],["bank_details","Bank details"]];return <div className="mt-6"><h3 className="font-semibold">Documents</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{types.map(([t,l])=>{const d=docs.find(x=>x.type===t);return <div key={t} className="flex items-center justify-between rounded-xl border p-3"><div className="min-w-0"><b className="block text-sm">{l}</b>{d?<a className="block truncate text-xs text-red-600" href={d.url} target="_blank">{d.fileName}</a>:<small className="text-stone-500">Not uploaded</small>}</div><label className="cursor-pointer rounded-lg bg-stone-100 px-3 py-2 text-xs font-semibold">{d?"Replace":"Upload"}<input hidden disabled={busy} type="file" accept=".pdf,image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)upload(t,f,d?._id)}}/></label></div>})}</div></div>}
function Field({name,label,type="text",optional=false,value}:{name:string;label:string;type?:string;optional?:boolean;value?:string}){const isCnic=name==="cnic";return <label className="text-sm font-medium">{label}<input name={name} type={type} required={!optional} defaultValue={value} inputMode={isCnic?"numeric":undefined} pattern={isCnic?"(?:[0-9][\\s-]*){13}":undefined} title={isCnic?"Enter exactly 13 digits, or leave this field empty":undefined} maxLength={isCnic?17:undefined} className={`${input} mt-1.5 w-full`}/></label>}
function Select({value,set,options}:{value:string;set:(v:string)=>void;options:string[]}){return <select className={input} value={value} onChange={e=>set(e.target.value)}><option value="">All</option>{options.map(x=><option key={x} value={x}>{x.replace("_"," ")}</option>)}</select>}
function Button({children,onClick,light,dark}:{children:React.ReactNode;onClick:()=>void;light?:boolean;dark?:boolean}){return <button onClick={onClick} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold ${light?"border bg-white":dark?"bg-stone-900 text-white":"bg-red-600 text-white"}`}>{children}</button>}
function Badge({admin}:{admin:boolean}){return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${admin?"bg-violet-100 text-violet-700":"bg-blue-100 text-blue-700"}`}>{admin?"Added by Admin ? No login":"Self-registered"}</span>}
function Status({value}:{value:string}){return <span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${value==="approved"?"bg-green-100 text-green-700":value==="rejected"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{value.replace("_"," ")}</span>}
function Metric({label,value}:{label:string;value:any}){return <div className="rounded-2xl border bg-white p-4"><p className="text-xs font-semibold uppercase text-stone-500">{label}</p><p className="mt-2 font-display text-2xl font-semibold">{value}</p></div>}
function Gate({text}:{text:string}){return <div className="mx-auto max-w-lg px-4 py-20 text-center"><h1 className="h1">Admin access</h1><p className="mt-3">{text}</p><Link className="mt-6 inline-block rounded-xl bg-red-600 px-5 py-3 text-white" href="/scholarship/login">Sign in</Link></div>}
function Loading(){return <div className="grid min-h-[60vh] place-items-center text-stone-500">Loading admin dashboard?</div>}
function err(x:unknown){if(x instanceof ConvexError){if(typeof x.data==="string")return x.data;if(x.data&&typeof x.data==="object"&&"message" in x.data)return String(x.data.message);return "Please check the entered information"}return x instanceof Error?x.message:"Something went wrong"}
